# CI de Nível 03 - Disparo após a conclusão de outra pipeline

#nome da pipe
name: 'CI - Execução Integrada'

# gatilhos / triggers -> regras de disparo
# gatilho por conclusão de outra pipeline - workflow_run

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['CI - Manual Execução', 'CI - Execução Agendada'] #nome da pipeline que vai disparar essa pipeline
    types:
      - completed

#tarefas executadas dentro da pipe
jobs:
  #nome do job
  inspecao:
    #maquina onde o job vai rodar
    runs-on: ubuntu-latest #git que vai disponibilizar a máquina virtual
    #validar se a pipeline anterior foi bem sucedida

    #passos do job
    steps:
      #clone do projeto
      - uses: actions/checkout@v4

      #instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      #instalação do yarn
      - name: Instalando do Yarn
        run: npm install -g yarn

      #instalação das dependências
      - name: Instalando dependências
        run: yarn


      - name: Inspenção de código
        run: yarn run lint

  unidade:
    runs-on: ubuntu-latest
    needs: [inspecao] #garante que o job de inspeção seja concluído antes de iniciar os testes unitários
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Instalando do Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn 

      - name: Executando os testes unitários
        run: yarn run test

  e2e:
    runs-on: ubuntu-latest
    needs: [inspecao]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
            node-version: latest

      - name: Instalando do Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      -name: Instalando browser do Playwright
        run: yarn playwright install
    
      #execução dos testes
      - name: Executando os testes
        run: yarn run e2e

  deploy:
    runs-on: ubuntu-latest
    needs: [unidade, e2e]
    steps:
      -name: Simulação de Deploy
        run: echo 'Deploy sendo realidado'


      

